### ISSUE TITLE
4_plot_mut_rate_from_RC_and_MM.ipynb is empty

### ISSUE THREAD

**Issue by rnaomics** [smyth-lab/Nano-DMS-MaP#1]
Hi

This file is empty. Could you check this?

Thanks

**Comment by patbohn** [comment]
Hi, 

Sorry for this, I updated the notebook with the code that should have been in there. 
One more thing, the code/notebooks for the Nature Methods paper are now located in this branch: https://github.com/smyth-lab/Nano-DMS-MaP/tree/NMethods-10.1038/s41592-023-01862-7 
with the main branch containing now a more streamlined example workflow. 

Best wishes, 
Patrick
